apiVersion: apps/v1
kind: Deployment
metadata:
  name: zagflightbooking-deployment
  labels:
    app: zagflightbooking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zagflightbooking-app
  template:
    metadata:
      labels:
        app: zagflightbooking-app
    spec:
      containers:
      - name: zagflightbooking-app
        image: raveenzag123/zagflight
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "myproject.settings.production"
